version: '3.8'

services:
  note-collab-service:
    build:
      context: ./wisepen-note-collab-service
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY}/wisepencloud-note-collab:${APP_VERSION:-latest}
    container_name: wisepen-note-collab-service
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - PROFILE=prod
      - NACOS_SERVER_ADDR=nacos:8848
      - NACOS_NAMESPACE=
      - NACOS_GROUP=DEFAULT_GROUP
      - PREFERRED_NETWORKS=
      - NACOS_USERNAME=${NACOS_USERNAME}
      - NACOS_PASSWORD=${NACOS_PASSWORD}
    volumes:
      - ../logs/note-collab:/logs
    networks:
      wisepen-net:
        aliases:
          - note-collab-service

networks:
  wisepen-net:
    external: true
    name: wisepen-net
